### ISSUE TITLE
generate_random_big_number

### ISSUE THREAD

**Issue by victorqribeiro** [ctsrc/simulated-victor-game#1]
Hi, I really like this and I'm flattered you decided to name it after me, but as I said before, I did not create the game. I just watched the video on youtube and decided to give it a go. Anyways, after I took a look at my code, I noticed a small bug on my function that generates big int (0..googol) and I fixed it. I think you could also do that on your code. Besides, on your function you're incrementing i twice:

https://github.com/ctsrc/simulated-victor-game/blob/gh-pages/simulate.js#L65

So you have consistent "empty" values on your array. Great work, never the less. Keep it up. =)

**Comment by ctsrc** [comment]
Thanks for spotting that, I saw the comment you wrote on HN about the double increment and fixed it. The other part you are referring to I guess is the part where digits that are zero are omitted. I figured that was intentional in your game so I did the same in my simulation but also updated my simulation to no longer to do that after seeing that it was not intended and that you had updated your game to not do it any longer :)

Let me know if you spot any other issues also, and keep it up you too :)
